//! Lockfile commands: generate a pinned snapshot of the venv, restore
//! the venv from such a snapshot, and detect drift between the two.
//!
//! Format is the simple pip-freeze style (`name==version` per line). It
//! is consumable by both `pip install -r` and `uv pip install -r`, so we
//! stay engine-agnostic. Saved by default at `<project>/requirements.lock`,
//! but the caller can override the path.

use crate::helpers::{
    classify_install_error, ensure_venv_dir, parse_pip_freeze, run_command_with_timeout,
    run_command_with_timeout_and_cancel, stdout_or_stderr,
};
use crate::jobs::{create_background_job, set_job_progress, set_job_status, AppState};
use crate::lockfile_report::build_drift_report;
use crate::package_managers::manager_for_engine;
use crate::types::DriftReport;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_LOCKFILE_NAME: &str = "requirements.lock";

fn resolve_lockfile_path(venv: &Path, override_path: Option<String>) -> PathBuf {
    match override_path.as_deref().filter(|s| !s.trim().is_empty()) {
        Some(p) => PathBuf::from(p),
        None => venv.parent().unwrap_or(venv).join(DEFAULT_LOCKFILE_NAME),
    }
}

fn freeze_text_with_cancel(
    venv: &Path,
    engine: &str,
    cancel: Option<&std::sync::atomic::AtomicBool>,
) -> Result<String, String> {
    let manager = manager_for_engine(engine)?;
    let mut cmd = manager.freeze_command(venv).to_command();
    let out = if let Some(cancel) = cancel {
        run_command_with_timeout_and_cancel(&mut cmd, 60, cancel)?
    } else {
        run_command_with_timeout(&mut cmd, 60)?
    };
    if out.status.success() {
        Ok(String::from_utf8_lossy(&out.stdout).to_string())
    } else {
        Err(format!(
            "{}: {}",
            manager.freeze_failure_prefix(),
            stdout_or_stderr(&out).trim()
        ))
    }
}

fn write_sorted_lockfile(target: &Path, freeze_output: &str) -> Result<(), String> {
    // Sort case-insensitively to keep diffs stable across reruns.
    let mut lines: Vec<&str> = freeze_output
        .lines()
        .map(|l| l.trim_end())
        .filter(|l| !l.is_empty())
        .collect();
    lines.sort_by_key(|a| a.to_lowercase());

    let mut body = String::with_capacity(freeze_output.len() + 64);
    body.push_str("# Generated by VOrchestra. Pinned snapshot of the virtual environment.\n");
    body.push_str("# Restore with: pip install -r requirements.lock (or uv pip install -r ...).\n");
    for l in lines {
        body.push_str(l);
        body.push('\n');
    }
    fs::write(target, body).map_err(|e| format!("Failed to write lockfile: {}", e))
}

fn ensure_pip_or_uv_lockfile_engine(engine: &str, action: &str) -> Result<(), String> {
    if matches!(engine, "pip" | "uv") {
        return Ok(());
    }

    Err(format!(
        "{} environments use native lockfile semantics. Use the native manager to {} dependencies.",
        engine, action
    ))
}

fn generate_lockfile_job(
    venv_path: String,
    engine: String,
    output_path: Option<String>,
    job: &crate::jobs::BackgroundJobHandle,
) -> Result<String, String> {
    ensure_pip_or_uv_lockfile_engine(&engine, "freeze")?;
    set_job_progress(job, "Freezing current environment...", Some(0.2));
    let venv = ensure_venv_dir(&venv_path)?;
    let target = resolve_lockfile_path(&venv, output_path);
    let freeze = freeze_text_with_cancel(&venv, &engine, Some(job.cancel.as_ref()))?;
    set_job_progress(job, "Writing lockfile...", Some(0.75));
    write_sorted_lockfile(&target, &freeze)?;
    set_job_progress(job, "Lockfile generated.", Some(0.95));
    Ok(format!("Lockfile written to {}", target.to_string_lossy()))
}

#[tauri::command]
pub fn start_generate_lockfile_job(
    venv_path: String,
    engine: String,
    output_path: Option<String>,
    state: tauri::State<'_, AppState>,
) -> Result<String, String> {
    let (job_id, job) = create_background_job(&state)?;
    tauri::async_runtime::spawn(async move {
        let blocking_job = job.clone();
        let outcome = tauri::async_runtime::spawn_blocking(move || {
            generate_lockfile_job(venv_path, engine, output_path, &blocking_job)
                .map(serde_json::Value::String)
        })
        .await
        .map_err(|e| e.to_string())
        .and_then(|res| res);

        match outcome {
            Ok(result) => set_job_status(&job, "success", Some(result), None),
            Err(err) if err == "Cancelled by user" => set_job_status(&job, "cancelled", None, None),
            Err(err) => set_job_status(&job, "error", None, Some(err)),
        }
    });
    Ok(job_id)
}

#[tauri::command]
pub fn start_restore_from_lockfile_job(
    venv_path: String,
    engine: String,
    lockfile_path: Option<String>,
    state: tauri::State<'_, AppState>,
) -> Result<String, String> {
    ensure_pip_or_uv_lockfile_engine(&engine, "restore or sync")?;
    let (job_id, job) = create_background_job(&state)?;
    tauri::async_runtime::spawn(async move {
        let blocking_job = job.clone();
        let outcome = tauri::async_runtime::spawn_blocking(move || {
            set_job_progress(&blocking_job, "Preparing lockfile restore...", Some(0.1));
            let venv = ensure_venv_dir(&venv_path)?;
            let target = resolve_lockfile_path(&venv, lockfile_path);
            if !target.exists() {
                return Err(format!(
                    "Lockfile not found at {}. Generate one first.",
                    target.to_string_lossy()
                ));
            }

            let manager = manager_for_engine(&engine)?;
            let mut cmd = manager
                .install_requirements_command(&venv, &target)
                .to_command();

            set_job_progress(
                &blocking_job,
                "Installing packages from lockfile...",
                Some(0.35),
            );
            let out =
                run_command_with_timeout_and_cancel(&mut cmd, 600, blocking_job.cancel.as_ref())?;
            if out.status.success() {
                set_job_progress(&blocking_job, "Lockfile restore finished.", Some(0.95));
                Ok(serde_json::Value::String(format!(
                    "Restored environment from {}",
                    target.to_string_lossy()
                )))
            } else {
                let stderr = String::from_utf8_lossy(&out.stderr).to_string();
                Err(classify_install_error(stderr))
            }
        })
        .await
        .map_err(|e| e.to_string())
        .and_then(|res| res);

        match outcome {
            Ok(result) => set_job_status(&job, "success", Some(result), None),
            Err(err) if err == "Cancelled by user" => set_job_status(&job, "cancelled", None, None),
            Err(err) => set_job_status(&job, "error", None, Some(err)),
        }
    });
    Ok(job_id)
}

fn compute_lockfile_drift_job(
    venv_path: String,
    engine: String,
    lockfile_path: Option<String>,
    job: &crate::jobs::BackgroundJobHandle,
) -> Result<DriftReport, String> {
    set_job_progress(job, "Reading lockfile...", Some(0.15));
    let venv = ensure_venv_dir(&venv_path)?;
    let target = resolve_lockfile_path(&venv, lockfile_path);
    if !target.exists() {
        return Err(format!(
            "Lockfile not found at {}. Generate one first.",
            target.to_string_lossy()
        ));
    }

    let lock_text =
        fs::read_to_string(&target).map_err(|e| format!("Failed to read lockfile: {}", e))?;
    let lock_map = parse_pip_freeze(&lock_text);

    set_job_progress(job, "Freezing live environment...", Some(0.45));
    let freeze = freeze_text_with_cancel(&venv, &engine, Some(job.cancel.as_ref()))?;
    let live_map = parse_pip_freeze(&freeze);

    set_job_progress(job, "Comparing package sets...", Some(0.75));
    let report = build_drift_report(lock_map, live_map, target.to_string_lossy().to_string());
    set_job_progress(job, "Drift check finished.", Some(0.95));
    Ok(report)
}

#[tauri::command]
pub fn start_compute_lockfile_drift_job(
    venv_path: String,
    engine: String,
    lockfile_path: Option<String>,
    state: tauri::State<'_, AppState>,
) -> Result<String, String> {
    let (job_id, job) = create_background_job(&state)?;
    tauri::async_runtime::spawn(async move {
        let blocking_job = job.clone();
        let outcome = tauri::async_runtime::spawn_blocking(move || {
            let report =
                compute_lockfile_drift_job(venv_path, engine, lockfile_path, &blocking_job)?;
            serde_json::to_value(report).map_err(|e| e.to_string())
        })
        .await
        .map_err(|e| e.to_string())
        .and_then(|res| res);

        match outcome {
            Ok(result) => set_job_status(&job, "success", Some(result), None),
            Err(err) if err == "Cancelled by user" => set_job_status(&job, "cancelled", None, None),
            Err(err) => set_job_status(&job, "error", None, Some(err)),
        }
    });
    Ok(job_id)
}

#[cfg(test)]
mod tests {
    use super::ensure_pip_or_uv_lockfile_engine;

    #[test]
    fn lockfile_write_actions_reject_read_only_native_managers() {
        assert!(ensure_pip_or_uv_lockfile_engine("pip", "freeze").is_ok());
        assert!(ensure_pip_or_uv_lockfile_engine("uv", "freeze").is_ok());

        let err = ensure_pip_or_uv_lockfile_engine("conda", "freeze").unwrap_err();
        assert!(err.contains("native lockfile semantics"));
    }
}
